name: Question
description: Ask a question about Cortex
title: "[Question]: "
labels: ["question", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Have a question about using Cortex? We're here to help!

        **Before asking**: Please check the [README](https://github.com/sahalkaabi2/cortex#readme) and [documentation](https://github.com/sahalkaabi2/cortex/tree/main/docs) first.

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: How do I...?
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Question Category
      description: What is your question about?
      options:
        - Setup & Installation
        - Configuration
        - Trading Modes (Paper/Live)
        - LLM Providers
        - Technical Indicators
        - Performance & Optimization
        - Deployment
        - API Keys
        - Database/Supabase
        - Docker
        - Troubleshooting
        - Other
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Please provide any relevant context for your question
      placeholder: |
        What have you tried so far?
        What are you trying to achieve?
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment (if relevant)
      description: Provide environment details if relevant to your question
      value: |
        - OS: [e.g., macOS, Windows, Linux]
        - Node.js version: [e.g., 18.17.0]
        - Cortex version: [e.g., 0.1.0]
        - Deployment: [e.g., Local, Docker, Synology NAS]
    validations:
      required: false

  - type: textarea
    id: attempts
    attributes:
      label: What I've Tried
      description: What have you already attempted to solve this?
      placeholder: I've tried...
    validations:
      required: false

  - type: checkboxes
    id: documentation
    attributes:
      label: Documentation Review
      description: Have you checked the documentation?
      options:
        - label: I have read the README
        - label: I have checked the troubleshooting section
        - label: I have searched existing issues

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Any other information that might be helpful
      placeholder: Additional context...
    validations:
      required: false
